config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :calendars, only: [:index]

  resources :locations, only: [:show]

  # You can have the root of your site routed with "root"
  root 'reservations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with
  # purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions
  # automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_class_for(type)}" }
    = message

app/views/shared/_header.html.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .container-fluid
    .navbar-header
      %button.navbar-toggle{ type: 'button',
                             'data-toggle' => 'collapse',
                             'data-target' => '#main-navbar-collapse' }
        %span.sr-only Colapsar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Paya Hotels', root_path, class: 'navbar-brand'

    #main-navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{ class: active_if(controller: 'reservations') }
          = link_to 'Reservas', reservations_path
        %li{ class: active_if(controller: 'calendars') }
          = link_to 'Planning', calendars_path
        - unless params[:controller] == 'reservations' && params[:action] == 'new'
          %li
            = link_to 'Nueva Reserva', new_reservation_path