config/routes.rb
Rails.application.routes.draw do
  resources :reservations

  resources :calendars, only: [:index]

  resources :locations, only: [:show]

  # You can have the root of your site routed with "root"
  root 'reservations#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with
  # purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions
  # automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/reservation.rb
#
# Represents a client reservation
#
class Reservation < ActiveRecord::Base
  CHANNELS = ['Paya', 'Booking', 'FHG', 'Primera Viaggi', 'Formentera Online',
              'FWeb', 'ITS', 'bodas', 'FRooms', 'Islamar', 'Paya Online',
              'Europlayas', 'FLibre', 'Trasmapi', 'Jumbo Tours', 'Fnatural',
              'Agencias', 'Roulette', 'ThomasCook']

  validates :channel, inclusion: { in: CHANNELS }

  validates :name, length: { maximum: 100 }

  has_many :rentals, inverse_of: :reservation, dependent: :destroy
  accepts_nested_attributes_for :rentals, allow_destroy: true

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def rentals_attributes=(attrs)
    super(attrs.each { |_k, v| v.delete('location') })
  end

  default_scope { order(created_at: :desc) }
end

app/controllers/reservations_controller.rb
#
# Most important controller in a Reservation Management app
#
class ReservationsController < ApplicationController
  before_action :_set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :_set_location, only: [:new, :create]

  # GET /reservations
  def index
    @reservations = Reservation.page(params[:page])
  end

  # GET /reservations/1
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @reservation.rentals.build(category: Category.first)
  end

  # POST /reservations
  def create
    @reservation = Reservation.new(_permitted_params)

    @reservation.save ? redirect_to(reservations_path) : render(action: :new)
  end

  # GET /reservations/1/edit
  def edit
  end

  # PUT /reservations/1
  def update
    if @reservation.update(_permitted_params)
      redirect_to(@reservation, notice: 'Reserva actualizada')
    else
      render(action: :edit)
    end
  end

  # DELETE /reservations/1
  def destroy
    @reservation.destroy
    redirect_to reservations_url, notice: 'Reserva borrada'
  end

  private

  def _set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def _set_location
    location_id = params[:location]
    @location = location_id ? Location.find(location_id) : Location.first
  end

  def _permitted_params
    params.require(:reservation)
      .permit(:code, :channel, :name, :price, rentals_attributes: [
        :id, :location, :category, :quantity, :arrival, :departure, :adults,
        :children, :babies, :_destroy])
  end
end

app/views/reservations/_form.html.haml
= simple_form_for @reservation, html: { class: 'form-horizontal' },
                  wrapper: :horizontal_form  do |f|

  = f.error_notification

  .form-inputs
    = f.input :code
    = f.input :channel, collection: Reservation::CHANNELS, include_blank: false
    = f.input :name

    #rentals
      = f.simple_fields_for :rentals do |rental|
        = render 'rental_fields', f: rental

      = link_to_add_rental 'Añadir Unidad', f

    = f.input :price, as: :string

  .form-actions
    = f.button :submit

app/views/reservations/_rental.html.haml
- reservation = rental.reservation
%tr
  %td= i == 0 ? link_to(reservation.code, reservation) : ''
  %td= i == 0 ? reservation.channel : ''
  %td= i == 0 ? reservation.name : ''
  %td= rental.location.name
  %td= rental.room.category.name
  %td= rental.arrival
  %td= rental.departure
  %td= rental.days
  %td= rental.adults
  %td= rental.children
  %td= rental.babies
  %td= i == 0 ? reservation.price : ''
  %td= i == 0 ? link_to('', reservation,
                        id: "delete-#{reservation.id}",
                        class: 'glyphicon glyphicon-remove', method: :delete,
                        data: { confirm: 'Estás segur@?' }) : ''

  %td= i == 0 ? link_to('', edit_reservation_path(reservation),
                        id: "edit-#{reservation.id}",
                        class: 'glyphicon glyphicon-pencil') : ''

app/views/reservations/_rental_fields.html.haml
-# FIXME: This is very thightly coupled to simple_form's code
.rental
  %span.form-group
    %label.col-sm-4.control-label
      Alojamiento
    .col-sm-3
      = f.input_field :location, collection: Location.all, include_blank: false
    .col-sm-3
      = f.input_field :category, collection: f.object.category.location.categories,
                      include_blank: false
    .col-sm-2
      = f.input_field :quantity, as: :select, collection: 1..5, value: 1,
                      include_blank: false

  %span.form-group
    %label.col-sm-4.control-label Llegada/Salida
    .col-sm-4
      = f.input_field :arrival, as: :string

    .col-sm-4
      = f.input_field :departure, as: :string

  %span.form-group
    %label.col-sm-4.control-label Adultos/Niños/Bebes

    .col-sm-2
      = f.input_field :adults, as: :select, collection: 1..5, value: 2, include_blank: false

    .col-sm-2
      = f.input_field :children, as: :select, collection: 0..5, value: 0, include_blank: false

    .col-sm-2
      = f.input_field :babies, as: :select, collection: 0..5, value: 0, include_blank: false

  - unless f.object.reservation.rentals.size <= 1
    %span.form_group
      = f.hidden_field :_destroy
      = link_to '', '#', class: 'glyphicon glyphicon-remove remove-fields'

app/views/reservations/edit.html.haml
.panel.panel-success
  .panel-heading
    .panel-title Editar Reserva #{@reservation.id}

  .panel-body
    .row
      .col-md-10
        = render 'form'

app/views/reservations/index.html.haml
%table.table.table-striped.reservations
  %thead
    %tr
      %th Localizador
      %th Canal
      %th Nombre
      %th Hotel
      %th Habitación
      %th Llegada
      %th Salida
      %th Días
      %th Adultos
      %th Niños
      %th Bebes
      %th Precio
      %th
      %th

  %tbody
    - @reservations.each do |reservation|
      - reservation.rentals.each_with_index do |rental, index|
        = render partial: 'rental', object: rental, locals: { i: index }

%ul.pager
  %li.previous= link_to_previous_page @reservations, 'Página Anterior'
  %li.next= link_to_next_page @reservations, 'Página Siguiente'

app/views/reservations/new.html.haml
.panel.panel-success
  .panel-heading
    .panel-title Nueva Reserva

  .panel-body
    .row
      .col-md-10
        = render 'form'

app/views/reservations/show.html.haml
.panel.panel-success
  .panel-heading
    .panel-links
      =link_to('', @reservation,
                   id: "delete-#{@reservation.id}",
                   class: 'glyphicon glyphicon-remove', method: :delete,
                   data: { confirm: 'Estás segur@?' })

      =link_to('', edit_reservation_path(@reservation),
                   id: "edit-#{@reservation.id}",
                   class: 'glyphicon glyphicon-pencil')
    .panel-title= "Reserva #{@reservation.id}"

  .panel-body
    %p
      %b Localizador:
      = @reservation.code

    %p
      %b Canal:
      = @reservation.channel

    %p
      %b Nombre:
      = @reservation.name

    %table.table
      %thead
        %tr
          %th
          %th Hotel
          %th Habitación
          %th Llegada
          %th Salida
          %th Adultos
          %th Niños
          %th Bebés

      %tbody
        - @reservation.rentals.each_with_index do |rental, i|
          %tr
            %td.header
              %b= "Alojamiento #{i > 0 ? i + 1 : ''}"
            %td= rental.location.name
            %td= rental.category.name
            %td= rental.arrival
            %td= rental.departure
            %td= rental.adults
            %td= rental.children
            %td= rental.babies

    %p
      %b Precio:
      = @reservation.price